spring.application.name=zodiacverseBackend

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/zodiacverse_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Ritvik@123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


app.jwt.secret=ZmFrZS1zZWNyZXQta2V5LWZvci16b2RpYWN2ZXJzZS1jaGFuZ2UtbWUtdG8tc29tZXRoaW5nLXNlY3VyZS1hbmQtbG9uZw==
app.jwt.access-expiration-ms=900000
app.jwt.refresh-expiration-ms=604800000
